id: P007953
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017511
  title: བཤད་རྒྱུད་ཀྱི་འགྲེལ་ཆེན་དྲི་མེད་ཀུན་གསལ
  author: ''
  volumes:
    f37870c87c00492999906c84199bfe87:
      image_group_id: I1PD454
      title: ''
      volume_number: 1
      total_pages: 634
ebook_metadata:
  title: བཤད་རྒྱུད་ཀྱི་འགྲེལ་ཆེན་དྲི་མེད་ཀུན་གསལ
  author: ''
  sku: P007953
  cover: cover.jpg
  layers:
  - pagination
