id: I8036D3BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:00:09+00:00'
last_modified: '2022-06-09T07:56:24.815019+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017511
  title: བཤད་རྒྱུད་ཀྱི་འགྲེལ་ཆེན་དྲི་མེད་ཀུན་གསལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C986:
      image_group_id: I1PD454
      title: Volume 1 of bshad rgyud kyi 'grel chen dri med kun gsal
      total_pages: 634
      order: 1
      base_file: C986.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
